# Generated by Django 5.0.6 on 2024-06-07 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_alter_blog_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='Date',
            field=models.CharField(max_length=500),
        ),
    ]
