# Generated by Django 5.0.6 on 2024-06-14 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0004_alter_blog_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='Date',
        ),
    ]
