# Generated by Django 5.0.6 on 2024-06-14 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0005_remove_blog_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='Date',
            field=models.DateField(null=True),
        ),
    ]
