# Generated by Django 5.0.6 on 2024-06-14 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0007_alter_blog_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='Title',
            field=models.CharField(max_length=50),
        ),
    ]
