# Generated by Django 5.0.6 on 2024-06-24 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0011_alter_blog_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='Description',
            field=models.CharField(max_length=1000),
        ),
    ]
